# Generated by Django 6.0.1 on 2026-02-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='OfficeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название канцтовара')),
            ],
            options={
                'verbose_name': 'Канцтовар',
                'verbose_name_plural': 'Канцтовары',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee', verbose_name='Сотрудник')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.officesupply', verbose_name='Канцтовар')),
            ],
            options={
                'verbose_name': 'Выдача канцтовара',
                'verbose_name_plural': 'Выдачи канцтоваров',
            },
        ),
    ]
